### ISSUE TITLE
VCMI stops responding

### ISSUE THREAD

**Issue by orekiyuji** [vdhan/An-Expansion#1]
![Screenshot 2024-06-25 160953](https://github.com/vdhan/an-expansion/assets/173811451/60a1ec87-6221-405b-828b-797e80813c34)
Hello, I have found a problem with this mod,
when the sub-mods which cast spells at the begining of the battle (Offence, Luck, Leadership, Armorer & Archery) are enabled, the game stops responding after a few battles.

**Comment by vdhan** [comment]
Thank you for your interest.
- How many mods are enabled? Which are they?
- Which version of VMCI?
- Can you share me the log file as well?

**Comment by orekiyuji** [comment]
Windows 11
VCMI 1.5.3
[VCMI_Client_log.txt](https://github.com/user-attachments/files/15984077/VCMI_Client_log.txt)
![Screenshot 2024-06-26 092433](https://github.com/vdhan/an-expansion/assets/173811451/0e31ed5c-7219-448b-bbc5-ccf1ac2d8b12)

**Comment by vdhan** [comment]
Hmm, there are too many mods. Because mods are developed by various authors, so they can be incompatible to each other. In this case, there are some potential incompatibility between:
- Submod "Skills" and "Simple Game Balance"
- Submod "Upgrade" and "Tides of War"

This mod is officially supports (compatible with) "Horn of the Abyss" and "In The Wake of Gods"
I appreciate your care, but please play one of potential incompatible mods above at the same time (not both)
